Start-Process "cmd" -ArgumentList "/k python node.py 127.0.0.1:5001 topologia_arvore_binaria/1.txt key_values/key_value1.txt"
Start-Process "cmd" -ArgumentList "/k python node.py 127.0.0.1:5002 topologia_arvore_binaria/2.txt key_values/key_value2.txt"
Start-Process "cmd" -ArgumentList "/k python node.py 127.0.0.1:5003 topologia_arvore_binaria/3.txt key_values/key_value3.txt"
Start-Process "cmd" -ArgumentList "/k python node.py 127.0.0.1:5004 topologia_arvore_binaria/4.txt key_values/key_value4.txt"
Start-Process "cmd" -ArgumentList "/k python node.py 127.0.0.1:5005 topologia_arvore_binaria/5.txt key_values/key_value5.txt"
Start-Process "cmd" -ArgumentList "/k python node.py 127.0.0.1:5006 topologia_arvore_binaria/6.txt key_values/key_value6.txt"
Start-Process "cmd" -ArgumentList "/k python node.py 127.0.0.1:5007 topologia_arvore_binaria/7.txt key_values/key_value7.txt"
