name: Test Nodes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

  run-node-1:
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        
    - name: Create command file
      run: |
        echo "1" > commands.txt
        echo "0" >> commands.txt
        echo "9" >> commands.txt

    - name: Run Node 1
      run: |
        cat commands.txt | python node.py 127.0.0.1:5001 topologia_arvore_binaria/1.txt key_values/key_value1.txt
        echo "Node 1 started"

